name: .NET

on:
  push:
    branches: [ main ]
    paths:
    - 'Kookaburra.SDK/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'Kookaburra.SDK/*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: './kookaburra.sdk'
      run: |
        cd 'Kookaburra.SDK'
        dotnet restore
    - name: Build
      working-directory: './kookaburra.sdk'
      run: |
        cd 'Kookaburra.SDK'
        dotnet build --no-restore
    - name: Test
      working-directory: './kookaburra.sdk'
      run: |
        cd 'Kookaburra.SDK'
        dotnet test --no-build --verbosity normal
