name: .NET

on:
  push:
    branches: [ main ]
    paths:
    - 'Kookaburra.SDK/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'Kookaburra.SDK/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore kookaburra.sdk/kookaburra.sdk.csproj
    - name: Build
      run: dotnet build --no-restore kookaburra.sdk/kookaburra.sdk.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal kookaburra.sdk/kookaburra.sdk.csproj
